services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: cqox-complete-grafana-1
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_USERS_DEFAULT_THEME=dark
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:Z,ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:Z,ro
    depends_on: []
    networks:
      - cqox-observe-net

networks:
  cqox-observe-net:
    external: true
