[project]
name = "cqox"
version = "0.1.0"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["/"]

[tool.black]
line-length = 100
target-version = ["py311"]
[tool.isort]
profile = "black"
[tool.ruff]
line-length = 100
